#!/bin/bash
vmname="win11"

state="$(sudo /bin/virsh dominfo win11 | grep State |  awk '{print $2}' )"



if [ "$state" == "running" ]; then
    running=true
else
    running=false
fi



if [ "$running" == "true" ]; then
    state="$(sudo /bin/virsh destroy win11)"

else
    state="$(sudo /bin/virsh start win11)"
fi